Resources:
  ImageStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.imageBucket}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: 
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
              - DELETE
            AllowedHeaders:
              - "*"
  ProcessingLambdaPermissionPhotosS3:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName:
        'Fn::GetAtt':
          - ProcessDashimageDashfnLambdaFunction
          - Arn
      Principal: "s3.amazonaws.com"
      Action: "lambda:InvokeFunction"
      SourceArn: !GetAtt ImageStore.Arn
Outputs:
  ImageBucket:
    Value:
      Ref: ImageStore