service: badge-scanner-api
app: badge-scanner-app
org: nguyen190887

plugins:
  - serverless-s3-sync
  - serverless-appsync-plugin
  - serverless-offline

custom:
  stage: ${self:provider.stage}
  websiteBucket: "tnn.badge-scanner-web-${self:custom.stage}"
  s3Sync:
    - bucketName: ${self:custom.websiteBucket}
      localDir: ../app/public
      acl: public-read
      followSymlinks: true
      defaultContentType: text/html
      params: # optional
        - index.html:
            CacheControl: 'no-cache'
        - "*.js":
            CacheControl: 'public, max-age=31536000'
  # appsync-offline:
  #   port: 62222
  appSync:
    region: ${self:provider.region}
    name: ${self:service.name}-${self:custom.stage}
    schema: schema.graphql
    authenticationType: API_KEY
    serviceRole: "${self:service.name}-AppSyncServiceRole"
    mappingTemplates:
      - type: Query
        dataSource: LambdaSource
        field: allPosts
        request: "common-request.vtl"
        response: "common-response.vtl"
    dataSources:
      - type: AWS_LAMBDA
        name: LambdaSource
        description: "Lambda DataSource"
        config:
          functionName: graphql-fn

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:*"
        - "log:*"
        - "rekognition:DetectText"
        - "s3:*"
      Resource: "*"

functions:
  badge-scanner-fn:
    handler: handler.index
    events:
      - http:
          path: badge/id
          method: post

  graphql-fn:
    handler: graphqlHandler.index

  process-image-fn:
    handler: processImageHandler.index
    events:
      - s3:
          bucket: tnn.image-badge-store-2
          events: s3:ObjectCreated:*
          
resources:
  - Resources:
      WebSite:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:custom.websiteBucket}
          AccessControl: PublicRead
          WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: index.html

  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
