name: Cleanup
on: delete

jobs:
  build:
    name: Serverless destroy action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo $GITHUB_REF; echo $GITHUB_HEAD_REF; echo $GITHUB_BASE_REF
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch
      # - uses: ./.github/actions/destroy
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
